### ISSUE TITLE
Latest-Symlinks

### ISSUE THREAD

**Issue by max06** [coreos/fedora-coreos-streams#556]
Hello Party-People!

I'm currently working on a tool to keep cloud images current in openstack. For this, I'd love to include your CoreOS with our list of default images. The project is not public yet, but that's just a matter of days.

To avoid updating the source definitions every time you release a new version, some non-changing urls to your latest builds (and their checksums) would be really awesome. 

Do you think you can add such latest-symlinks? Do you need more details?

Thanks a lot in advance!

**Comment by lucab** [comment]
Hi and welcome :wave:

We do provide a set of machine-friendly metadata that you can use for this purpose, the full list is at https://github.com/coreos/fedora-coreos-tracker/tree/main/metadata. In particular, for your usecase, you'd want to use the "stream metadata".

We do not provide stable URL redirectors due to several concerns. You can read more about that at https://github.com/coreos/fedora-coreos-tracker/issues/625.

**Comment by max06** [comment]
Hello @lucab 

That was damn quick!

The issue is: I implemented latest symlinks because every other distribution I added so far offers them. As example for ubuntu:
```yaml
release: "jammy jellyfish"
url: https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64.img
checksum: https://cloud-images.ubuntu.com/releases/jammy/release/SHA256SUMS
version: 22.04
```
Those urls never change and always point to the latest release.

For this case I'd have to implement special handling for your images, which is something I'd like to prevent. 

Do you want to rethink this? Or are you able to update a yaml file in my (going to be) public repository when you publish a new version?

Have a great day!
